#docker compose up -d 

version: "3.9"
name: "In-Book"

services: 
  db:
    build: ./backend/database/
    restart: always
    container_name: db_inbook
    expose:
    - 3306
    networks:
      - PHPNetwork
      - DBNetwork
    
  phpmyadmin_gestore:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prova
    ports:
      - "9090:80"  #per settare porte devo rifare la creazione del compose
    networks:
      - PHPNetwork
  
  webserver:
    build: ./backend/config/
    container_name: backend
    depends_on:
      - db
    environment:
      - NODE_ENV=production
    ports:
      - 4000:8080
    networks:
      - DBNetwork
    volumes:
      - ./backend/:/app/backend/
      - ./frontend/:/app/frontend/
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json

networks:
    DBNetwork:
        driver: bridge
    PHPNetwork:
        driver: bridge
