#docker compose up -d

version: "3.9"
name: "In-Book"

services:
    db:
        build: ./backend/database/
        restart: always
        container_name: db_inbook
        ports:
            - "3306:3306" #per testare il db lo espongo all'esterno
        networks:
            - PHPNetwork
            - DBNetwork

    phpmyadmin_gestore:
        image: phpmyadmin
        container_name: phpmyadmin
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: prova
        ports:
            - "9090:80" #per settare porte devo rifare la creazione del compose
        networks:
            - PHPNetwork

    webserver:
        build: ./backend/config/
        container_name: backend
        depends_on:
            - db
        environment:
            - NODE_ENV=production
        expose:
            - 4000
        networks:
            - DBNetwork
        volumes:
            - ./backend/:/app/backend/
            - ./frontend/:/app/frontend/
            - ./package.json:/app/package.json
            - ./package-lock.json:/app/package-lock.json

    keycloak:
        build: ./keycloak/
        container_name: keycloak
        depends_on:
            - db
        expose:
            - 8080
            - 8443
        networks:
            DBNetwork:
                aliases:
                    - keycloak.inbook.local

    reverseproxy:
        container_name: nginx
        hostname: keycloak.inbook.local
        image: nginx
        depends_on:
          - db
          - webserver
        command: ["./wait-for-it.sh", "backend:4000","--","nginx", "-g", "daemon off;"]
        ports:
            - 80:80
            - 433:433
        volumes:
            - ./nginx/conf:/etc/nginx
            - ./nginx/private:/etc/ssl/private
            - ./nginx/wait-for-it.sh:/wait-for-it.sh
        networks:
          - DBNetwork

networks:
    DBNetwork:
        driver: bridge
    PHPNetwork:
        driver: bridge
