
CREATE DATABASE ACCESS_CREDENTIALS;

CREATE TABLE `ACCESS_CREDENTIALS`.`LOGIN`(
  	ID char(16) NOT NULL UNIQUE  PRIMARY KEY,
    Email varchar(30) NOT NULL UNIQUE,
    Password_user varchar(40) NOT NULL,
    Created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
