CREATE DATABASE `KEYCLOAK`;
GRANT ALL PRIVILEGES ON `KEYCLOAK`.* TO 'administrator'@'%';

CREATE TRIGGER copy_keycloak_user AFTER INSERT ON `KEYCLOAK`.`USER_ENTITY`
BEGIN
  INSERT INTO `INBOOK`.`UTENTI` (ID,Nome,Cognome,Email) VALUES (`NEW`.`ID` ,`NEW`.`FIRST_NAME` ,`NEW`.`LAST_NAME` ,`NEW`.`EMAIL`);
  UPDATE `INBOOK`.`UTENTI` SET `Data_di_nascita` = (SELECT `VALUE` FROM `KEYCLOAK`.`USER_ATTRIBUTE` WHERE `USER_ID` = `NEW`.`ID` AND NAME='dob') WHERE `INBOOK`.`ID` =`NEW`.`ID`;
  UPDATE `INBOOK`.`UTENTI` SET `Telefono` = (SELECT `VALUE` FROM `KEYCLOAK`.`USER_ATTRIBUTE` WHERE `USER_ID` = `NEW`.`ID` AND NAME='mobile') WHERE `INBOOK`.`ID` =`NEW`.`ID`;
END;