DELIMITER $$
CREATE PROCEDURE procedura_bella (OLD_FIRST_NAME_u VARCHAR(255), ID_u VARCHAR(36), FIRST_NAME_u VARCHAR(255), LAST_NAME_u VARCHAR(255), EMAIL_u VARCHAR(255))
BEGIN
  DECLARE telefono_utente VARCHAR(30);
  DECLARE data_nascita DATE;
  
  set telefono_utente := (SELECT VALUE FROM KEYCLOAK.USER_ATTRIBUTE WHERE USER_ID = ID_u AND NAME='mobile');
  set data_nascita := (SELECT STR_TO_DATE(VALUE,'%Y-%m-%d') FROM KEYCLOAK.USER_ATTRIBUTE WHERE USER_ID = ID_u AND NAME='dob');
  
  IF OLD_FIRST_NAME_u is NULL THEN
    INSERT INTO INBOOK.UTENTI (ID,Nome,Cognome,Email,Telefono,Data_di_nascita,Tipo) VALUES (ID_u ,FIRST_NAME_u ,LAST_NAME_u ,EMAIL_u, telefono_utente, data_nascita,"Cliente");
  END IF;
END;
$$
DELIMITER ;

CREATE TRIGGER `pippozzo_trigger` AFTER UPDATE ON KEYCLOAK.`USER_ENTITY`
  FOR EACH ROW call procedura_bella(OLD.FIRST_NAME,NEW.ID, NEW.FIRST_NAME ,NEW.LAST_NAME ,NEW.EMAIL);