CREATE DATABASE KEYCLOAK;
GRANT ALL PRIVILEGES ON KEYCLOAK.* TO 'administrator'@'%';

delimiter //
CREATE TRIGGER copy_keycloak_user
AFTER INSERT
ON KEYCLOAK.USER_ENTITY FOR EACH ROW
BEGIN
  INSERT INTO INBOOK.UTENTI (ID,Nome,Cognome,Email,Tipo)
  VALUES (NEW.ID,NEW.FIRST_NAME,NEW.LAST_NAME,NEW.EMAIL,'Cliente');
  UPDATE INBOOK.UTENTI SET Data_di_nascita = (SELECT VALUE FROM KEYCLOAK.USER_ATTRIBUTE WHERE USER_ID = NEW.ID AND NAME='dob');
  UPDATE INBOOK.UTENTI SET Telefono = (SELECT VALUE FROM KEYCLOAK.USER_ATTRIBUTE WHERE USER_ID = NEW.ID AND NAME=mobile);
END;//
delimiter ;